[audio]
enable_sounds = true

[bar]
backgroundOpacity = 1
capsuleOpacity = 1
exclusive = true
floating = false
hideOnOverview = false
marginHorizontal = 4
marginVertical = 4
monitors = []
order = [ "widgets" ]
outerCorners = true
position = "left"
screenOverrides = []
showCapsule = false
showOutline = false
useSeparateOpacity = false

    [bar.widgets]
    center = [ "audio_visualizer" ]
    end = [ "notifications", "tray", "battery", "control-center", "session" ]
    margin_ends = 600
    start = [ "group:g1", "volume", "brightness" ]
    widget_spacing = 12

        [[bar.widgets.capsule_group]]
        accordion = true
        accordion_direction = "end"
        enabled = true
        fill = "on_secondary"
        id = "g1"
        members = [ "clock", "date" ]
        opacity = 0.0
        padding = 6.0

[calendar]
enabled = true

    [calendar.account.personal_google]
    type = "google"

[config]

[control_center]
show_shortcut_labels = false

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
enabled = false
monitors = []
position = "bottom"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
address = "Brescia, Italy"

[lockscreen]
blur_intensity = 0.19999999552965164
edge_smoothness = 0.19999999552965164
fingerprint = false
transition = [ "disc", "honeycomb", "stripes", "wipe" ]
transition_duration = 1000

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
border = false
history_retention_hours = 8
keep_dismissed_in_history = false
layer = "overlay"
max_visible = 3

[osd]
border = false
enabled = true
monitors = []

[shell]
button_borders = false
card_borders = false
clipboard_image_action_command = "qimgv {path}"
input_borders = false
lang = "en"
niri_overview_type_to_launch_enabled = true
password_style = "random"
popup_borders = false
screen_time_enabled = true
show_location = false

    [shell.animation]
    speed = 1.2500000186264515

    [shell.greeter_sync]
    auto_sync = true

    [shell.launcher.providers.session]
    global = true

    [shell.panel]
    borders = false
    session_position = "center"
    wallpaper_placement = "floating"

    [shell.screen_corners]
    enabled = true

    [shell.screenshot]
    confirm_region = true
    remember_last_region = true

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "suspend"
    command = "notify-send 'Noctalia' 'Custom session entry'"
    countdown_seconds = 0.0
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[templates.openrgb]
input_path = "/nix/store/ajx5qbngk73d18cz2qzxcmzc009i5724-openrgbTemplate.sh"
output_path = "/home/fabibo/.config/OpenRGB/noctaliaTemplate.sh"
post_hook = "bash /home/fabibo/.config/OpenRGB/noctaliaTemplate.sh"

[templates.sioyek]
input_path = "/nix/store/24a0zlmqvhcahacx0xs0g29ivdjhw1c0-sioyekTemplate.config"
output_path = "/home/fabibo/.config/sioyek/colorscheme.config"

[[templates.activeTemplates]]
enabled = true
id = "zenBrowser"

[[templates.activeTemplates]]
enabled = true
id = "discord"

[[templates.activeTemplates]]
enabled = true
id = "spicetify"

[[templates.activeTemplates]]
enabled = true
id = "niri"

[[templates.activeTemplates]]
enabled = true
id = "kitty"

[[templates.activeTemplates]]
enabled = true
id = "gtk"

[theme]
community_palette = "Catppuccin Frappe Mauve"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "kitty", "niri" ]
    community_ids = [ "spicetify", "zen-browser", "discord" ]

[wallpaper]
directory = "/home/fabibo/Pictures/Wallpapers"
enabled = true

    [wallpaper.default]
    path = "/home/fabibo/Pictures/Wallpapers/wallhaven-pow2wp_1920x1080.png"

    [wallpaper.last]
    path = "/home/fabibo/Pictures/Wallpapers/wallhaven-pow2wp_1920x1080.png"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/fabibo/Pictures/Wallpapers/wallhaven-pow2wp_1920x1080.png"

[widget.audio_visualizer]
anchor = true

    [widget.audio_visualizer.actions]
    left = "panel-toggle control-center media"

[widget.control-center]
glyph = "settings-2"

[widget.date]
format = "{:%d/%m}"

[widget.media]
album_art_only = true
hide_when_no_media = true
interactive = false

[widget.notifications]
hide_when_no_unread = true

[widget.tray]
drawer = true

[widget.volume]
show_label = false
